apiVersion: v1
kind: Secret
metadata:
  name: "{{ include \"ai-trading-bot.fullname\" . }}-secret"
  labels: {}
type: Opaque
stringData:
  ALPACA_API_KEY: "{{ .Values.secrets.alpacaApiKey }}"
  ALPACA_API_SECRET: "{{ .Values.secrets.alpacaApiSecret }}"